### ISSUE TITLE
Remove trailing slash in direct button href

### ISSUE THREAD

**Issue by alexcroox** [wesbos/Cloudapp-Cloudflare-Fix#1]
Noticed the "Direct" button doesn't work in your README example because you have a trailing slash:

https://wes.io/d5uybeNB/

which this line https://github.com/wesbos/Cloudapp-Cloudflare-Fix/blob/main/src/index.ts#L26

then generates: `https://wes.io/d5uybeNB//content` (double slash)

**Comment by wesbos** [comment]
oh thanks! Will fix in 1 sec

**Comment by wesbos** [comment]
fixed!
